### ISSUE TITLE
test: MockDatabaseAdminServiceImplTest.deleteBackup is flaky

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#221]
`MockDatabaseAdminServiceImplTest.deleteBackup` is flaky.

```
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.cloud.spanner.MockDatabaseAdminServiceImplTest.createTestBackup(MockDatabaseAdminServiceImplTest.java:333)
	at com.google.cloud.spanner.MockDatabaseAdminServiceImplTest.deleteBackup(MockDatabaseAdminServiceImplTest.java:368)
```

**Comment by olavloite** [comment]
Closing as this flake hasn't been seen in a long time.
