### ISSUE TITLE
io.opentelemetry class not found exception

### ISSUE THREAD

**Issue by bizfing** [googleapis/java-spanner#2275]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-spanner/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   Google Cloud Spanner - Google Standard Query Used

2. OS type and version: Windows 10 64bit
4. Java version: OpenJdk 19 
5.  version(s): google-cloud-spanner 6.17.4

#### Steps to reproduce

  1. Spring Boot Application's versions
		> springboot.version: 2.7.4
		> java.version: 17
		> spring-cloud-gcp.version: 3.0.0
		> spring-cloud.version: 2021.0.3
		> spanner-hibernate-dialect.version: 1.3.0

  2. Maven pom.xml dependencies
`
	<dependencies>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-spanner-hibernate-dialect</artifactId>
			<version>${spanner-hibernate-dialect.version}</version>
		</dependency>
	</dependencies> 
`

 3. ClassNotFoundException encountered.
 3.1 java.lang.ClassNotFoundException: io.opentelemetry.opencensusshim.OpenTelemetryTraceComponentImpl
 `
java.lang.ClassNotFoundException: io.opentelemetry.opencensusshim.OpenTelemetryTraceComponentImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:467) ~[na:na]
	at io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:96) ~[opencensus-api-0.30.0.jar:0.30.0]
	at io.opencensus.trace.Tracing.<clinit>(Tracing.java:38) ~[opencensus-api-0.30.0.jar:0.30.0]
	at com.google.cloud.spanner.SpannerImpl.<clinit>(SpannerImpl.java:58) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:458) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:453) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540) ~[google-cloud-core-2.3.5.jar:2.3.5]
	at com.google.cloud.spring.autoconfigure.spanner.GcpSpannerAutoConfiguration$CoreSpannerAutoConfiguration.spanner(GcpSpannerAutoConfiguration.java:195) ~[spring-cloud-gcp-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.bizfing.api.BizfingApiProjectApplication.main(BizfingApiProjectApplication.java:10) ~[classes/:na]
`

 3.2 io.opencensus.trace.Tracing              : Couldn't load full implementation for TraceComponent, now trying to load lite implementation.
`
2023-02-10 06:41:33.350 DEBUG 11564 --- [           main] io.opencensus.trace.Tracing              : Couldn't load full implementation for TraceComponent, now trying to load lite implementation.

java.lang.ClassNotFoundException: io.opencensus.impl.trace.TraceComponentImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:467) ~[na:na]
	at io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:111) ~[opencensus-api-0.30.0.jar:0.30.0]
	at io.opencensus.trace.Tracing.<clinit>(Tracing.java:38) ~[opencensus-api-0.30.0.jar:0.30.0]
	at com.google.cloud.spanner.SpannerImpl.<clinit>(SpannerImpl.java:58) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:458) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:453) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540) ~[google-cloud-core-2.3.5.jar:2.3.5]
	at com.google.cloud.spring.autoconfigure.spanner.GcpSpannerAutoConfiguration$CoreSpannerAutoConfiguration.spanner(GcpSpannerAutoConfiguration.java:195) ~[spring-cloud-gcp-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.bizfing.api.BizfingApiProjectApplication.main(BizfingApiProjectApplication.java:10) ~[classes/:na]
`

 3.3 io.grpc.ManagedChannelRegistry           : Unable to find OkHttpChannelProvider
`
2023-02-10 06:41:33.665 DEBUG 11564 --- [           main] io.grpc.ManagedChannelRegistry           : Unable to find OkHttpChannelProvider

java.lang.ClassNotFoundException: io.grpc.okhttp.OkHttpChannelProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:375) ~[na:na]
	at io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:134) ~[grpc-api-1.43.2.jar:1.43.2]
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:98) ~[grpc-api-1.43.2.jar:1.43.2]
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41) ~[grpc-api-1.43.2.jar:1.43.2]
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[grpc-api-1.43.2.jar:1.43.2]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:357) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(InstantiatingGrpcChannelProvider.java:82) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:240) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:250) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:228) ~[gax-grpc-2.8.1.jar:2.8.1]
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:205) ~[gax-2.8.1.jar:2.8.1]
	at com.google.cloud.spanner.v1.stub.GrpcSpannerStub.create(GrpcSpannerStub.java:231) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.<init>(GapicSpannerRpc.java:404) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.<init>(GapicSpannerRpc.java:295) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:468) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:463) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560) ~[google-cloud-core-2.3.5.jar:2.3.5]
	at com.google.cloud.spanner.SpannerOptions.getSpannerRpcV1(SpannerOptions.java:1304) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerImpl.<init>(SpannerImpl.java:132) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:458) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:453) ~[google-cloud-spanner-6.17.4.jar:6.17.4]
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540) ~[google-cloud-core-2.3.5.jar:2.3.5]
	at com.google.cloud.spring.autoconfigure.spanner.GcpSpannerAutoConfiguration$CoreSpannerAutoConfiguration.spanner(GcpSpannerAutoConfiguration.java:195) ~[spring-cloud-gcp-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.bizfing.api.BizfingApiProjectApplication.main(BizfingApiProjectApplication.java:10) ~[classes/:na]
`

#### Code example

 Just Spring Boot Main Class for testing.

#### Stack trace
```
Google Cloud Spanner on Hibernate was successfully connected.

`
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.4)

2023-02-10 07:16:05.413  INFO 6104 --- [           main] c.b.api.BizfingApiProjectApplication     : Starting BizfingApiProjectApplication using Java 17.0.6 on jangsunjin with PID 6104 (D:\workspace\bizfing\bizfing-api-project\target\classes started by jangsunjin in D:\workspace\bizfing\bizfing-api-project)
2023-02-10 07:16:05.419 DEBUG 6104 --- [           main] c.b.api.BizfingApiProjectApplication     : Running with Spring Boot v2.7.4, Spring v5.3.23
2023-02-10 07:16:05.420  INFO 6104 --- [           main] c.b.api.BizfingApiProjectApplication     : No active profile set, falling back to 1 default profile: "default"
2023-02-10 07:16:05.421 DEBUG 6104 --- [           main] o.s.boot.SpringApplication               : Loading source class com.bizfing.api.BizfingApiProjectApplication
2023-02-10 07:16:05.542 DEBUG 6104 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@76012793
2023-02-10 07:16:06.139  INFO 6104 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Spanner repositories in DEFAULT mode.
2023-02-10 07:16:06.146 DEBUG 6104 --- [           main] o.s.b.a.AutoConfigurationPackages        : @EnableAutoConfiguration was declared on a class in the package 'com.bizfing.api'. Automatic @Repository and @Entity scanning is enabled.
2023-02-10 07:16:06.148 DEBUG 6104 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Scanning for Spanner repositories in packages com.bizfing.api.
2023-02-10 07:16:06.161  INFO 6104 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11 ms. Found 0 Spanner repository interfaces.
2023-02-10 07:16:06.642 DEBUG 6104 --- [           main] c.g.a.oauth2.DefaultCredentialsProvider  : Attempting to load credentials from file: D:\git\bizfing\bf-1-api-be\src\main\resources\cert\bf-1-prod-all-spanner-db-user-cert.json
2023-02-10 07:16:06.699  INFO 6104 --- [           main] c.g.c.s.core.DefaultCredentialsProvider  : Default credentials provider for service account bf-1-prod-all-spanner-db-user@bizfing.iam.gserviceaccount.com
2023-02-10 07:16:06.699  INFO 6104 --- [           main] c.g.c.s.core.DefaultCredentialsProvider  : Scopes in use by default credentials: [https://www.googleapis.com/auth/pubsub, https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data, https://www.googleapis.com/auth/datastore, https://www.googleapis.com/auth/sqlservice.admin, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/devstorage.read_write, https://www.googleapis.com/auth/cloudruntimeconfig, https://www.googleapis.com/auth/trace.append, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-vision, https://www.googleapis.com/auth/bigquery, https://www.googleapis.com/auth/monitoring.write]
2023-02-10 07:16:06.702  INFO 6104 --- [           main] c.g.c.s.a.c.GcpContextAutoConfiguration  : The default project ID is xxxxxx
2023-02-10 07:16:06.729  INFO 6104 --- [           main] c.g.c.s.core.DefaultCredentialsProvider  : Default credentials provider for service account bf-1-xxxxxxx-spanner-db-user@xxxxxx.iam.gserviceaccount.com
2023-02-10 07:16:06.729  INFO 6104 --- [           main] c.g.c.s.core.DefaultCredentialsProvider  : Scopes in use by default credentials: [https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data]
2023-02-10 07:16:06.968 DEBUG 6104 --- [           main] io.opencensus.trace.Tracing              : Couldn't load full implementation for OpenTelemetry TraceComponent, now trying to load original implementation.
`

#### External references such as API reference guides

I adding some dependencies, but ClassNotFoundException is not cleared.

`
<!-- https://cloud.google.com/blog/products/spanner/troubleshooting-cloud-spanner-applications-with-opencensus-metrics -->
  <dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-impl</artifactId>
    <version>0.31.1</version>
    <scope>runtime</scope>
  </dependency>
  <dependency>
    <groupId>io.opencensus</groupId>
    <artifactId>opencensus-contrib-observability-ready-util</artifactId>
    <version>0.31.1</version>
    <scope>runtime</scope>
  </dependency>
`

#### Any additional information below

I many changed all of springboot, google-cloud-spanner-dialect, google-cloud-spanner, grpc or others version on maven pom.xml.
But It issue not cleared.
So please check it.
Thanks.

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by bizfing** [comment]
I solve the this issue.

It's happen by spring-cloud-gcp-dependencies BOM.

spring-cloud-gcp-dependencies has two contributor that **org.springframework.cloud** and **com.google.cloud like blew**

`
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>${spring-cloud-gcp.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
`

`
			<dependency> <== REAL
				<groupId>com.google.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>${google-cloud-spring.version}</version> 
				<type>pom</type>
				<scope>import</scope>
			</dependency>
`

I removed the org.springframework.cloud's spring-cloud-gcp-dependencies.

And reconfigurationed.

Thanks !
