### ISSUE TITLE
com.google.cloud.spanner.it.ITQueryOptionsTest.executeUpdate Fails for 100000

### ISSUE THREAD

**Issue by sid-dinesh94** [googleapis/java-spanner#249]
Looking at:

https://github.com/googleapis/java-spanner/blob/f4fa6bfca4bb821cbda426c4cb7bf32f091a2913/google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java#L168

I see that the test was intended for Version 100,000. But Version 10,000 was provided to the run command.

The comment does say that for version 100,000 the backend should safely ignore it. At least for version 10,000 the backend does not ignore and in fact throws an error:
```
com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Query optimizer version: 10000 is not supported
	at com.google.cloud.spanner.it.ITQueryOptionsTest.executeUpdate(ITQueryOptionsTest.java:157)
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Query optimizer version: 10000 is not supported
	at com.google.cloud.spanner.it.ITQueryOptionsTest.executeUpdate(ITQueryOptionsTest.java:157)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Query optimizer version: 10000 is not supported
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Query optimizer version: 10000 is not supported
```

A fix might be to add a zero to Line 168; but i do not have full context of this test.

**Comment by skuruppu** [comment]
Thanks for the report @sid-dinesh94. @olavloite has the context regarding this test failure so he should be able to get a fix out.
