### ISSUE TITLE
Struct Object Equality Isn't Value-Based

### ISSUE THREAD

**Issue by senbrow** [googleapis/java-spanner#2610]
#### Environment details

OS type and version: `Linux Mint 5.15.0-79-generic #86-Ubuntu`
Java version: `20`
Spanner Java Library Version: `6.42.3`

#### Steps to reproduce

1. Read an `ARRAY` of `STRUCT`s in a query into a `ResultSet`
2. Compare the `STRUCT` contents to manually-constructed Java `Struct` objects.
3. Observe that value-equality still results in a "not equal" outcome.

#### Code example

EXAMPLE 1 (list of structs):

```java
    DatabaseClient client = <...>;
    var resultSet =
        client.singleUse().executeQuery(Statement.of(
            """
            SELECT ARRAY<STRUCT<INT64, STRING>>[
                STRUCT(1 AS x, \"foo\" AS y)
            ]
            AS StructList"""));

    assertThat(resultSet.next()).isTrue();
    assertThat(resultSet.getStructList("StructList")).containsExactly(
        Struct.newBuilder()
            .set("x").to(1L)
            .set("y").to("foo")
            .build()
    );
```

Result:
```
org.junit.ComparisonFailure: 
Expecting actual:
  [[1, foo]]
to contain exactly (and in same order):
  [[1, foo]]
but some elements were not found:
  [[1, foo]]
and others were not expected:
  [[1, foo]]
 expected:<[[1, foo]] ([ArrayList@36f1046f])> but was:<[[1, foo]] ([UnmodifiableRandomAccessList@692fd26])>
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
```

EXAMPLE 2 (piecewise comparison):

```java
    DatabaseClient client = <...>;
    var resultSet =
        client.singleUse().executeQuery(Statement.of(
            """
            SELECT ARRAY<STRUCT<INT64, STRING>>[
                STRUCT(1 AS x, \"foo\" AS y)
            ]
            AS StructList"""));

    assertThat(resultSet.next()).isTrue();
    assertThat(resultSet.getStructList("StructList")).element(0).isEqualTo(
        Struct.newBuilder()
            .set("x").to(1L)
            .set("y").to("foo")
            .build()
    );
```

Result:
```
java.lang.AssertionError: [List element at index 0] 
expected: "[1, foo] (ValueListStruct@3157e4c0)"
 but was: "[1, foo] (GrpcStruct@4e31c3ec)"
```

**Comment by senbrow** [comment]
Note: the examples above connect to an emulated spanner instance running in a local Docker container to evaluate the SQL.

**Comment by arpan14** [comment]
@senbrow It looks like there could be a mismatch of types for `.set("x").to(1L)` and `INT64`. I'll attempt to confirm this further and get back.

**Comment by arpan14** [comment]
I don't think this is a valid query. When I try to execute this against a Spanner table from the cloud console, I get the below error

```
Statement failed: Unsupported query shape: This query returns a STRUCT value constructed by a scalar subquery or struct construction syntax. Spanner does not yet support returning STRUCT except as arrays-of-structs. Rephrase your query to produce the struct value with an array subquery: ARRAY(SELECT AS STRUCT expr ...) or flatten the structs fields into the result.
```

Could you send a valid select statement against a Spanner table?
