### ISSUE TITLE
DatabaseClient write transactions timeout error after running job for a few hours

### ISSUE THREAD

**Issue by iceriver123** [googleapis/java-spanner#3315]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-spanner/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: GCP kubernetes cluster 
3. Java version: 17
4.  version(s): 6.65.0

#### Steps to reproduce

  When we upgrade spanner library from 6.57.0 to 6.65.0, the jobs start to have spanner write timeout error after running for 6 to 18 hours. This happens usually on massive writes with high writes-per-second (e.g., hundreds of writes per seconds). We don't know if this has anything to do with session leaks or not, but 1) We already enabled setWarnAndCloseIfInactiveTransactions on SessionPool options. 2) We don't see this problem on 6.57.0. Our guess is some code between 6.58.0 to 6.65.0 causing the issue.

#### Code example

For instance, the following code will trigger it

spannerClient
          .readWriteTransaction(Options.tag("method=writeToTable"))
          .run(
              transaction -> {
                transaction.buffer(
                    toInsertOrUpdateMutation(
                        deviceId,
                        uploadId,
                        orgId,
                        mergedMeasure,
                        measureQueryTimestamp,
                        /* dedupBucketSizeSeconds= / null,
                        / randomNumber= */ null));
                return null;
              });

#### Stack trace
```
....
com.google.cloud.spanner.SpannerRetryHelper.runTxWithRetriesOnAborted(SpannerRetryHelper.java:79), com.google.cloud.spanner.SpannerRetryHelper.runTxWithRetriesOnAborted(SpannerRetryHelper.java:68), com.google.cloud.spanner.TransactionRunnerImpl.runInternal(TransactionRunnerImpl.java:1183), com.google.cloud.spanner.TransactionRunnerImpl.run(TransactionRunnerImpl.java:1096), com.google.cloud.spanner.SessionPool$SessionPoolTransactionRunner.run(SessionPool.java:1002), 
...
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by iceriver123** [comment]
Some update: We started to notice this issue when upgrading spanner client from 6.57 to 6.58. Maybe it is related to the max_delay setting introduced in 6.58?

**Comment by kberezin-nshl** [comment]
@sakthivelmanii we observe this issue. Java Library version 6.96.1

```
com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: CallOptions deadline exceeded after 3599.999643157s. Name resolution delay 0.000000000 seconds. [closed=[], committed=[remote_addr=spanner.googleapis.com/173.194.195.95:443]] - Statement: <REDACTED>
    at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:396)
    at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:223)
    at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:135)
    at com.google.cloud.spanner.GrpcStreamIterator.computeNext(GrpcStreamIterator.java:147)
    at com.google.cloud.spanner.GrpcStreamIterator.computeNext(GrpcStreamIterator.java:38)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at com.google.cloud.spanner.ResumableStreamIterator.computeNext(ResumableStreamIterator.java:266)
    at com.google.cloud.spanner.ResumableStreamIterator.computeNext(ResumableStreamIterator.java:56)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at com.google.cloud.spanner.GrpcValueIterator.ensureReady(GrpcValueIterator.java:141)
    at com.google.cloud.spanner.GrpcValueIterator.computeNext(GrpcValueIterator.java:58)
    at com.google.cloud.spanner.GrpcValueIterator.computeNext(GrpcValueIterator.java:36)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at com.google.cloud.spanner.GrpcStruct.consumeRow(GrpcStruct.java:258)
    at com.google.cloud.spanner.GrpcResultSet.next(GrpcResultSet.java:102)
...
```

The symptoms are the same: the job has started 1 hour ago and crashed with this after an hour (well, it's obvious from the exception), here are our logs:
```
INFO 2025-08-05T23:02:44.814Z --- SpannerClient was created. Took 520.7 ms
<...>
ERROR 2025-08-06T00:02:52.011Z --- Error: com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: CallOptions deadline ...
```

Extra 8 seconds is probably because we do some stuff before we first start writing to Spanner. Clearly a problem for us here, as we have multiple 1+ hour jobs that may run during the day. 

We need a fix and a workaround for that, @sakthivelmanii @rahul2393

**Comment by sakthivelmanii** [comment]
@kberezin-nshl Yes. you can change the default timeouts.
