### ISSUE TITLE
Sessions with active transactions being reused with AsyncTransactionManager

### ISSUE THREAD

**Issue by SanjayVas** [googleapis/java-spanner#3403]
When using `AsyncTransactionManager` in a multi-threaded environment, I often get the following error when calling `commitAsync()`:

```
commit can only be invoked if the transaction is in progress. Current state: ROLLED_BACK
```

Stepping through with a debugger, it appears that this is due to `invalidate()` being called on the active transaction in the session when calling `beginAsync()` on a separate `AsyncTransactionManager` instance. The implication here is that the session is being reused for this new transaction despite having an existing transaction that's still active.

One interesting point is that the transaction state of the `AsyncTransactionManager` instance is actually `STARTED` at this point. It's the *delegate* transaction manager that has a transaction state of `ROLLED_BACK`.

#### Environment details

1. API: Spanner
2. OS type and version: Linux (Debian Trixie)
3. Java version: 17
4.  version(s): 6.74.0

#### Steps to reproduce

  1. Use `AsyncTransactionManager` as described in the example in the documentation for `DatabaseClient.transactionManagerAsync()` in a multi-threaded environment.

#### Stack trace
```
Caused by: java.lang.IllegalStateException: commit can only be invoked if the transaction is in progress. Current state: ROLLED_BACK
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at com.google.cloud.spanner.AsyncTransactionManagerImpl.commitAsync(AsyncTransactionManagerImpl.java:118)
	at com.google.cloud.spanner.SessionPoolAsyncTransactionManager.lambda$commitAsync$1(SessionPoolAsyncTransactionManager.java:192)
	at com.google.api.core.ApiFutures$5.apply(ApiFutures.java:367)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:224)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:124)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1298)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:762)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:44)
	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:453)
	at com.google.api.core.ApiFutures.transformAsync(ApiFutures.java:362)
	at com.google.cloud.spanner.SessionPoolAsyncTransactionManager.commitAsync(SessionPoolAsyncTransactionManager.java:187)
	at com.google.cloud.spanner.TransactionContextFutureImpl$AsyncTransactionStatementImpl$2.onSuccess(TransactionContextFutureImpl.java:165)
	at com.google.api.core.ApiFutures$1.onSuccess(ApiFutures.java:89)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1135)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1298)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:762)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1101)
	at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:79)
	at com.google.cloud.spanner.TransactionContextFutureImpl$AsyncTransactionStatementImpl.commitAsync(TransactionContextFutureImpl.java:153)
...
```

#### Additional information

The only reason I'm using `AsyncTransactionManager` directly as opposed to `AsyncRunner` is to work around #2698. Ideally `AsyncRunner` would be truly asynchronous/non-blocking rather than just making blocking calls in another thread.

**Comment by SanjayVas** [comment]
This turned out to be an issue in my Kotlin adapter.
