### ISSUE TITLE
test: DatabaseAdminClientTest sometimes fails

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#391]
DatabaseAdminClientTest sometimes fails with:

```
[INFO] Running com.google.cloud.spanner.DatabaseAdminClientTest
[ERROR] Tests run: 42, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.382 s <<< FAILURE! - in com.google.cloud.spanner.DatabaseAdminClientTest
[ERROR] com.google.cloud.spanner.DatabaseAdminClientTest.instanceListBackups  Time elapsed: 0.551 s  <<< ERROR!
com.google.cloud.spanner.SpannerException: UNKNOWN: com.google.cloud.spanner.SpannerException: CANCELLED: Task was cancelled.
	at com.google.cloud.spanner.DatabaseAdminClientTest.restoreTestBackup(DatabaseAdminClientTest.java:830)
	at com.google.cloud.spanner.DatabaseAdminClientTest.setUp(DatabaseAdminClientTest.java:212)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spanner.SpannerException: CANCELLED: Task was cancelled.
	at com.google.cloud.spanner.DatabaseAdminClientTest.restoreTestBackup(DatabaseAdminClientTest.java:828)
	at com.google.cloud.spanner.DatabaseAdminClientTest.setUp(DatabaseAdminClientTest.java:212)
Caused by: com.google.cloud.spanner.SpannerException: CANCELLED: Task was cancelled.
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
```

**Comment by olavloite** [comment]
This hasn't happened in the meantime, and I just tried to execute the test more than 1,000 times locally without a single failure. Closing for now.
