### ISSUE TITLE
com.google.cloud.spanner.it.ITAsyncAPITest.invalidDatabase is flaky

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#432]
```
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.392 s <<< FAILURE! - in com.google.cloud.spanner.it.ITAsyncAPITest
[ERROR] com.google.cloud.spanner.it.ITAsyncAPITest.invalidDatabase  Time elapsed: 0.039 s  <<< ERROR!
com.google.cloud.spanner.DatabaseNotFoundException: 
NOT_FOUND: The session pool has been invalidated because a previous RPC returned 'Database not found': NOT_FOUND: com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Database not found: projects/gcloud-devel/instances/test-instance-48129262/databases/invalid
resource_type: "type.googleapis.com/google.spanner.admin.database.v1.Database"
resource_name: "projects/gcloud-devel/instances/test-instance-48129262/databases/invalid"
description: "Database does not exist."

	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:203)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:56)
	at com.google.cloud.spanner.SessionPool.getReadSession(SessionPool.java:2046)
	at com.google.cloud.spanner.DatabaseClientImpl.getReadSession(DatabaseClientImpl.java:56)
	at com.google.cloud.spanner.DatabaseClientImpl.singleUse(DatabaseClientImpl.java:119)
```

**Comment by olavloite** [comment]
Closing, has not occurred since.
